<?php
return [
    "Confirm Password",
    "Please confirm your password before continuing.",
    "Email",
    "Send Password Reset Link",
    "Reset Password",
    "Retype Password",
    "New Password",
    "Old Password",
    "Submit",
    "Code",
    "Didn\'t get Code? Click to",
    "Resend code",
    "Your Email Address is",
    "Verify Your Email",
    "Your Phone Number is",
    "Verify Your Phone",
    "Github",
    "Facebook",
    "Google",
    "Remember me on the device ?",
    "Captcha Code",
    "Password",
    "Username",
    "Passwords do not match",
    "Repeat Password",
    "Phone...",
    "Select Country",
    "User Name",
    "Last Name",
    "First Name",
    "You don't have permission to access ‘/’ on",
    "Forbidden",
    "Back To Home",
    "this server",
    "found",
    "Page not",
    "Allowed",
    "Method Not",
    "has expired",
    "Sorry, your session",
    "Please contact the server administrator.",
    "The server encountered an internal error misconfiguration and was unable to complete your request.",
    "Internal Server Error",
    "Reply",
    "Cancel",
    "Reply to",
    "Popular Tags",
    "Categories",
    "Recent Feeds",
    "Search",
    "Post Comment",
    "Show Replies",
    "Reply",
    "Comments",
    "Social Share",
    "Admin",
    "Recent Feeds",
    "Read More",
    "Travelers Information",
    "Phone: ",
    "Email: ",
    "Edit",
    "Contact Details",
    "Gross Total",
    "Discount",
    "Total Amount",
    "Discount Summary",
    "Coupon code",
    "Number of Infant",
    "Number of Children",
    "Number of Adult",
    "Duration",
    "Date",
    "Departure date",
    "Tour type",
    "Your booking",
    "Payment",
    "Payment Information",
    "Travelers Information",
    "Phone: ",
    "Email: ",
    "Edit",
    "Contact Details",
    "Payment Summery",
    "Selected Crypto Currency",
    "Select Crypto Currency",
    "confirm and continue",
    "I agree to the",
    "terms and conditions.",
    "Select Currency",
    "Supported Currency",
    "Select Payement",
    "No payment methods available",
    "Payment Summery",
    "Payment Details",
    "Next",
    "Message",
    "Country",
    "ZIP code/Postal code",
    "State/Province/Region",
    "City",
    "Address Line 2",
    "Address Line 1 *",
    "Phone *",
    "Email *",
    "Last Name *",
    "First Name *",
    "Contact Info",
    "discount Image",
    "Book Now and Enjoy Amazing Savings!".
    "Book Now",
    "Location",
    "Area(km2)",
    "Currency Used",
    "Languages Spoken",
    "Visa Requirements",
    "Country",
    "Destination Info",
    "View in Map",
    "Experience the Difference",
    "Review Overview",
    "FEATURED",
    "person",
    "Country",
    "State",
    "Address",
    "Avg Rating",
    "Copy Profile",
    "Packages",
    "Member since",
    "Submit Reviews",
    "Your comments...",
    "Guides",
    "Foods",
    "Safety",
    "Places",
    "Hotel",
    "Services",
    "Add Your Reviews",
    "Reviews",
    "Clients Reviews",
    "from",
    "from ",
    "Profile Copied",
    "Guide Details",
    "Next",
    "Previous",
    "How Can I Help You?",
    "Chat with ",
    "Need any help?",
    "Book Now",
    "Total",
    "Infant",
    "Children",
    "Adults",
    "Tickets",
    "Time:",
    "From Date:",
    "Tour Booking",
    "by sell",
    "by view",
    " High to Low ",
    " Low to High ",
    "Asc",
    "Date",
    "Desc",
    "Advanced",
    "Select Destination",
    "Go Back",
    "We couldn't find what you're looking for. Please try again later or modify your search.",
    "No Data Found",
    "Amenities",
    "Price:",
    "Filter by Price",
    "Select Country",
    "Select Category",
    "Category",
    "Destination",
    "Advance Search",
    "Load More",
    "Filter by Price",
    "Search here",
    "Destination",
    "Home",
    "Type above and press Enter to search. Press Close to cancel.",
    "Explore More",
    "Dashboard",
    "Next",
    "Previous",
    "Install",
    "More",
    "No Result Found",
    "Confirm",
    "Confirm your interest to renew. The plan will automatically renew after your current one ends.",
    "Kyc Settings",
    "Support Ticket",
    "Payment Logs",
    "Tour History",
    "Manage Gateway",
    "Manage Team",
    "Chats",
    "Add",
    "List",
    "Packages",
    "Dashboards",
    "Sign out",
    "Install PWA",
    "2FA Verification",
    "Auto Renew Plan",
    "Notification Permissions",
    "Profile & account",
    "Clear all messages",
    "Clear all notifications",
    "No Notifications Found",
    "Notifications",
    "No Messages Found",
    "Messages",
    "Search for a menu",
    "Brand Image",
    "e.g. John Doe",
    "e.g. johndoe@gmail.com",
    "Destination",
    "Places",
    "Phone",
    "Useful Links",
    "Quick Links",
    "Gallery",
    "Select a slot",
    "Select Duration",
    "Continue Reading",
    "Read More",
    "Purchase Now",
    " Featured Listing",
    " Listing Items Allowed",
    " Validity",
    "Read More",
    " Tours ",
    "How Can I Help You?",
    "chats",
    "Chats",
    "Set nickname",
    "Setup a nickname",
    "Nickname Setup",
    "Deleting this conversation is permanent. Are you absolutely sure you want to proceed?",
    "Confirm Deletion",
    "You don't have any active chats.",
    "Click On Any Conversation.",
    "Customer",
    "Owner",
    "Chat List is empty here!.",
    "messages",
    "Close",
    "Admin Feedback",
    "Payment Information",
    "of",
    "Showing:",
    "Action",
    "Date",
    "Status",
    "Amount",
    "Method",
    "Serial",
    "Transaction ID",
    "Date Range",
    "Clear Filters",
    "Filter",
    "Search logs",
    "Payment Logs",
    "Set nickname",
    "Nickname Setup",
    "Setup a nickname",
    "Currency Symbol",
    "currency rate auto update?",
    "Do you want to",
    "Confirmation",
    "Save changes",
    "Fixed Charge",
    "Percentage Charge",
    "Max Limit",
    "Min Limit",
    "Conversion Rate",
    "Auto Update Currency",
    "Supported Currencies Configuration",
    "To test your payment gateway, set up a sandbox environment.",
    "Test Environment",
    "Enable to your gateway status",
    "Browse your file here",
    "parameters",
    "Supported Currency",
    "Name",
    "No data to show",
    "Supported Currency",
    "Gateway Currencies",
    "Payment Methods",
    "Payment Gateways",
    " pixels.",
    "For better resolution, please use an image with a size of",
    "Browse your file here",
    "Thumbnail",
    "Description",
    "Destignation",
    "Tour Completed",
    "Guide Code",
    "Years of experience",
    "Name",
    "Add new Guide",
    "Create Guides",
    "Guides",
    "Edit Guide",
    "Edit Guides",
    "Are you sure you want to change the status of this item? This action cannot be undone and will affect the current status of the item.",
    "Code",
    "Status",
    "rating",
    "Tour Completed",
    "Experience",
    "Transaction ID",
    "Search guides",
    "Tour Guides",
    "Package Images",
    "Package Details",
    "What We Expect",
    "Excluded Facility",
    "Included Facility",
    "Longitude",
    "Latitude",
    "Map",
    "Time Slot(s)",
    "Price For Adult",
    "Price For Children",
    "Price For Infant",
    "Select Places",
    "Amenities",
    "Guides",
    "Minimum Travelers",
    "Maximum Travelers",
    "Tour Duration",
    "Video Link",
    "Tour Time Slot",
    "Create Package",
    "Packages",
    "Package Edit",
    "e.g. Les Corts, 08028 Barcelona, Spain",
    "Update",
    "Do you want to inactive all selected data?",
    "Are you sure you want to change the status of this item? This action cannot be undone and will affect the current status of the item.",
    "Do you want to delete all selected data?",
    "Are you sure you want to set this item as a featured item. ",
    "Discount Type",
    "Do you want to delete this Package",
    "Created at",
    "Time Slot",
    "Search Packages",
    "Packages",
    "Accept",
    "Reject",
    "Transaction ID:",
    "Total Price:",
    "Total Infants:",
    "Total Children:",
    "Total Adults:",
    "Package Title: ",
    "Search history",
    "Package Booking",
    "Final Amount : ",
    "Discount Amount : ",
    "Coupon Apply : ",
    "Receivable Amount : ",
    "Total Price : ",
    "Charge In Payment Currency: ",
    "Booking ID : ",
    "Payment Information",
    "Make it Completed",
    "Make it Refund",
    "Approve Tour",
    " Information",
    "Booking Created Date",
    "Booking Date",
    "Total Price",
    "Expired",
    "Tour Pending",
    "Completed",
    "Refunded",
    "Payment Pending",
    "Booking Calender",
    "Last month",
    "This month",
    "Total Sell",
    "Total view",
    "Rejected",
    "Approved",
    "reason",
    "Submitted",
    "Fields",
    "KYC Type",
    "Kyc History",
    "Select Kyc Type",
    "KYC Verification",
    "Kyc Settings",
    "Save changes",
    "Notification Template List is empty here!.",
    "We need permission from your browser to show notifications.",
    "Request permission",
    "Notifications Permissions",
    "Profile",
    "User Profile",
    "Save changes",
    "Linkedin Link",
    "Instagram Link",
    "Twitter Link",
    "Facebook Link",
    "Prefered Language",
    "Location",
    "Text about me",
    "About Me",
    "Zip Code",
    "Address Two",
    "e.g. david",
    "Address One",
    "Full name",
    "Delete account",
    "Basic information",
    "Choose Files",
    "Create Ticket",
    "Last Reply",
    "Clear Filters",
    "Date Range",
    "Closed",
    "Customer Reply",
    "Answered",
    "All Status",
    "Search tickets",
    "Support Ticket",
    "Do you want to closed this ticket?",
    "File(s)",
    "Support Ticket View",
    "Choose Files",
    "Create Ticket",
    "Package Title: ",
    "Booking Information",
    "Total Person",
    "Paid Amount",
    "Package Title",
    "Search history",
    "Tour History",
    "Are you want to Re-generate Authenticator ?",
    "Re-generate Confirmation",
    "Verify that\'s you, to Disable 2FA",
    "Enter Google Authenticator Code",
    "Verify Your OTP",
    "DOWNLOAD APP",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Two Factor Authenticator",
    "Copy",
    "Disable Two Factor Authenticator",
    "Re-generate",
    "Two Step Security",
    "Search history",
    "Tour History",
    "Become a Vendor",
    "Balance: "
];
